### PR TITLE
Fix UV Index behaviour

### LINKED ISSUE #35: UV Threshold behaviour
Hi,

I've recently updated from my fork (where I implemented UV threshold).

I'm a little confused with the logic, as of now I have the UV limit set to '3' and the position set to fully closed (default). Using winter mode (to maximise light), currently the blind keeps closing with status 'UV index below threshold', surely it should be open then, to maximise light (sun is in window right now)?

### PR DESCRIPTION
**Pull request by benderl**
This should fix #35

### CODE REVIEW

**Comment by alisdairjsmyth** [comment]
@benderl - thanks for the fix and the German translation (which I have assumed to be correct)

**Comment by benderl** [comment]
At least it should be. But I forgot the translation for the multiblind controller. Will submit another PR soon.

**Comment by benderl** [comment]
Do you have any clue, why the version got updated in git and npm but is not proposed as an update in node-red?

**Comment by alisdairjsmyth** [comment]
No idea.  From what I gather the "Node-Red Flow Library" indexes any
package in the npm repository containing the "node-red" keyword.  The
keyword remains in the package.json, and npm has been updated - for
whatever reason the library has not refreshed.

**Comment by benderl** [comment]
Seems like they disabled the auto update feature:
[https://discourse.nodered.org/t/how-to-add-update-nodes-to-the-flow-library/25294](url)

**Comment by alisdairjsmyth** [comment]
Thanks - I have requested a refresh.

**Pull request merged**
