### PR TITLE
Improvements on Winter Mode

### PR DESCRIPTION
**Pull request by jonferreira**
Following our discussion [here](https://github.com/alisdairjsmyth/node-red-contrib-blindcontroller/issues/3) I've made some changes  to make the Winter Mode more similar to Summer Mode (and a few other bits).
So far it seems to be working just fine

### CODE REVIEW

**Comment by alisdairjsmyth** [comment]
I have reviewed the changes contained in this Pull Request.  

From what I can ascertain three changes have been made to blindcontroller.js
- **Replication of "Summer" logic to "Winter"**.  The replication of this logic undoes the original request to maximise rather than constrain sunlight - the behaviour for Summer and Winter will now be the same. i.e. Mode no longer would drive a difference in behaviour.
- **Change to the logic of setting blindPositionExpiry**.  The original logic recalculated the position expiry each time a position was manually set.  The proposed logic will only calculate an expiry if a value is not set.  The implication being that a manually set position could immediately expire.
- **Persistence of height as an attribute of blind**.  Height was originally viewed as an internal temporary variable that was used to calculate the blind position, and therefore deliberately not exposed outside the node.
I have issue with each of these changes and consequently do not intend to merge them.

The pull request also includes a change to sunpos.js to allow the node to take a timestamp as an input and use it as the basis of the sun position calculation.  I have no issue with this change - it is a great idea.

Since all changes are included in a single Pull Request - my proposal is replicate the proposed changes to sunpos.js directly on the master branch and close this Pull Request without merging it.

**Comment by jonferreira** [comment]
I have to say I’m a bit puzzled by your comments – don’t take me wrong!

Replication of "Summer" logic to "Winter" – this won’t do the same, it will do the opposite of Summer Mode, i.e. if Summer Mode says to set 60% Winter Mode will say 40% thus maximizing the light explosion. Tests done on my system seem to show this is working as intended although I may be missing something?

Change to the logic of setting blindPositionExpiry – I see what you mean although I’m from the opinion if a user manually set “something” then we should respect it, even if it sounds like an error. The idea behind this was to allow values other than a fixed 2 hours interval.

Persistence of height as an attribute of blind – I’ve added this mostly for debug, it was extremely useful to understand the “logic behind” but sure, it can be removed.

**Comment by alisdairjsmyth** [comment]
My mistake - upon closer inspection it is not an exact replication of the logic.  (You were right to be puzzled)

That said, I am still puzzled as to why setting the position to **maxopen** doesn't achieve the goal of maximising direct sunlight into the room?

**Comment by jonferreira** [comment]
:-)

I do understand what you mean and "maybe" I can add a third option Winter Mode, Gradual maximize sunlight?
Long story short I haven't bought any curtains and the wife doesn't like to see the shutters fully opened unless absolutely needed...plus it's "funny" to track the sun position and open the shutters to the exact position needed lol

**Comment by alisdairjsmyth** [comment]
The influence of wives ... this project came about by asking why my wife was positioning the blinds the way she was.  Her motivation was to protect our furniture from harmful UV.

I am trying to convert "doesn't like to see the shutters fully opened unless absolutely needed" into a goal or requirement.  With the existing implementation **maxopen** provides the mechanism for supporting "not fully opened" - and "unless absolutely needed" is the manual override??

**Comment by jonferreira** [comment]
well the logic behind is *if* the house needs to be warmer and *if* it's hot enough/not too cloudy outside then it's worth to open the roller shutters "more than usual" (all roller shutters are set to 50% when I wake up).
In my old system what I had was a series of calculations to track sun azimuth/altitude and set the shutters to the "exact" (well it's never an exact science) position where the sun would be hitting the wall/roller shutter.
So unless the sun is lets say at 80% of the roller shutter (down to bottom) then there's no need for it fo be fully opened - makes sense?

**Pull request merged**
